apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: assign-wordpress
  namespace: kbb-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.7.2
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: metrics.enabled
          value: 'true'
    chart: mysql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: assgn
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true