apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-genrator-or-superapp
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: prod
            dirname: wordpress
            project: assgn
          - env: dev
            dirname: wordpress
            project: assgn
  template:
    metadata:
      name: 'assgn-wordpress-{{env}}'
      namespace: argocd
    spec:
      project: default

      source:
        directory:
          recurse: true
        path: 'manifests/{{env}}/{{dirname}}'
        repoURL: https://github.com/desert3agle/argo-test.git
        targetRevision: HEAD
      destination: 
        server: https://kubernetes.default.svc
        namespace: 'assgn-{{env}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
