apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: assgn-wordpress
  namespace: argocd
spec:
  project: default

  source:
    directory:
      recurse: true
    path: manifests/wordpress
    repoURL: https://github.com/desert3agle/argo-test.git
    targetRevision: HEAD

  destination: 
    server: https://kubernetes.default.svc
    namespace: assgn
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
